### ISSUE TITLE
Invalid "main" field in objectorarray package.json breaks endent

### ISSUE THREAD

**Issue by LucaBlackDragon** [indentjs/endent#9]
`endent` depends on `objectorarray` which has an error in its package.json, it declares `"main": "dist/index.js"` but the package published on npm does not contain a `/dist` folder:

![image](https://user-images.githubusercontent.com/3714010/122062856-1306f400-cdf0-11eb-8910-5dfd2a00dd49.png)

This is causing all sorts of issues with `endent`.
For example, if you try to compile an app containing `endent` with Rollup or Vite, the build command will fail with this error:

`[commonjs] Failed to resolve entry for package "objectorarray". The package may have incorrect main/module/exports specified in its package.json`

Node.js 16 is also showing a warning with a similar content:

`DeprecationWarning: Invalid 'main' field in '\node_modules\objectorarray\package.json' of 'dist/index.js'`

I'm opening an issue here because I believe that @zhouhanseng is one of the authors of both `endent` and `objectorarray`.
There are two open issues ([issue 3](https://github.com/indentjs/objectorarray/issues/3) and [issue 7](https://github.com/indentjs/objectorarray/issues/7)) about this in the `objectorarray` repo.

**Comment by hanszhoou** [comment]
@LucaBlackDragon 

Fixed by https://github.com/zhouhanseng/objectorarray/commit/d5021ac64ed9147ceaedcb97a1c8156f0143018b.

[endent@2.1.0](https://www.npmjs.com/package/endent) released.

PS. Could you please help me to close this issue, since I lost my 2 factor authentic token, this project has moved to https://github.com/zhouhanseng/endent

**Comment by LucaBlackDragon** [comment]
Thanks!
